# Generated by Django 2.1.1 on 2018-10-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('true_name', models.CharField(default='', max_length=32, null=True, verbose_name='真实姓名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('phone', models.IntegerField(default=888888, null=True, verbose_name='手机号码')),
                ('wx', models.CharField(default='', max_length=32, null=True, verbose_name='微信号')),
                ('address', models.CharField(default='', max_length=100, null=True, verbose_name='地址')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name_plural': '用户表管理',
            },
        ),
    ]
