# Generated by Django 2.1.1 on 2018-10-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=1, verbose_name='性别'),
        ),
    ]
