# Generated by Django 2.1.1 on 2018-10-30 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20181030_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pic_name', models.CharField(max_length=32, verbose_name='图集名称')),
                ('pic_intro', models.CharField(default='', max_length=32, verbose_name='图集简介')),
                ('pic_img', models.ImageField(default='static/upload/%Y-%m-%d/', max_length=128, upload_to='static/upload/%Y-%m-%d/', verbose_name='封面路径')),
                ('pic_hot', models.IntegerField(default=1, verbose_name='点击量')),
                ('pic_weight', models.IntegerField(default=1, verbose_name='权重')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('pic_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.User', verbose_name='发布作者')),
            ],
            options={
                'verbose_name_plural': '图片表管理',
            },
        ),
    ]
