# Generated by Django 2.1.1 on 2018-10-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='pic_kind',
            field=models.IntegerField(choices=[(1, '宽图'), (2, '方图'), (3, '长图')], default=1, verbose_name='图片类别'),
        ),
    ]
