# Generated by Django 2.1.1 on 2018-10-31 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_pic_pic_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picd_name', models.CharField(max_length=32, verbose_name='图片名称')),
                ('picd_weight', models.IntegerField(default=1, verbose_name='图片权重')),
                ('picd_intro', models.CharField(default='', max_length=128, verbose_name='图片介绍')),
                ('picd_img', models.ImageField(default='static/upload/%Y-%m-%d/', max_length=128, upload_to='static/upload/%Y-%m-%d/', verbose_name='图片地址')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('for_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.Pic', verbose_name='所属图册')),
            ],
            options={
                'verbose_name_plural': '图集详情表管理',
            },
        ),
    ]
