# Generated by Django 2.1.1 on 2018-10-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0007_picdetail_picd_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='pic_use',
            field=models.IntegerField(choices=[(1, '上线'), (2, '下线')], default=1, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='picdetail',
            name='picd_use',
            field=models.IntegerField(choices=[(1, '上线'), (2, '下线')], default=1, verbose_name='是否启用'),
        ),
    ]
