# Generated by Django 2.1.1 on 2018-10-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0009_auto_20181031_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='pic_img',
            field=models.FileField(default='static/upload/%Y-%m-%d/', max_length=128, upload_to='static/upload/%Y-%m-%d/', verbose_name='封面路径'),
        ),
    ]
