# Generated by Django 2.1.1 on 2018-11-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0010_auto_20181031_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_log',
            field=models.IntegerField(choices=[(1, '上线'), (2, '下线')], default=2, verbose_name='是否在线'),
        ),
    ]
