# Generated by Django 2.1.1 on 2018-11-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0011_user_is_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=32, verbose_name='性别'),
        ),
    ]
