# Generated by Django 2.1.1 on 2018-11-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0012_auto_20181101_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='pic_sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=32, verbose_name='图片男女'),
        ),
    ]
