# Generated by Django 2.1.1 on 2018-11-01 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0013_pic_pic_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='pic_sex',
        ),
    ]
