# Generated by Django 2.1.1 on 2018-11-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0019_auto_20181103_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '图集评论表管理'},
        ),
        migrations.AlterModelOptions(
            name='picdetail',
            options={'verbose_name_plural': '图集表详情管理'},
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=1, verbose_name='性别'),
        ),
    ]
