# Generated by Django 2.1.1 on 2018-11-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
    ]
