# Generated by Django 2.1.1 on 2018-11-03 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0020_auto_20181103_1455'),
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='for_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='picture.User', verbose_name='发布者'),
        ),
    ]
